/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Options.*;
import Program.Main;

/**
 *
 * @author MAJ
 */
public class AdminMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminMenuPanel
     */
    public AdminMenuJPanel() {
        initComponents();
        Main.login.setMinimumSize(this.getMinimumSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlejLabel = new javax.swing.JLabel();
        UserMenujPanel = new javax.swing.JPanel();
        EditaUserJButton = new javax.swing.JButton();
        ReportsJButton = new javax.swing.JButton();
        ExitJButton = new javax.swing.JButton();
        AddaUserJButton = new javax.swing.JButton();
        ChangePasswordJButton = new javax.swing.JButton();
        AssetMenujPanel = new javax.swing.JPanel();
        ViewAllAssetsJButton = new javax.swing.JButton();
        AddanAssetJButton = new javax.swing.JButton();
        EditanAssetJButton = new javax.swing.JButton();
        RetireanAssetJButton = new javax.swing.JButton();
        RepairanAssetsJButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(450, 480));
        setPreferredSize(new java.awt.Dimension(450, 480));

        TitlejLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlejLabel.setText("Menu");

        UserMenujPanel.setBackground(new java.awt.Color(153, 153, 153));

        EditaUserJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditaUserJButton.setText("Edit a User ");
        EditaUserJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditaUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditaUserJButtonActionPerformed(evt);
            }
        });

        ReportsJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ReportsJButton.setText("Reports ");
        ReportsJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReportsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsJButtonChangePasswordJButtonActionPerformed(evt);
            }
        });

        ExitJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitJButton.setText("Exit");
        ExitJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitJButtonChangePasswordJButtonActionPerformed(evt);
            }
        });

        AddaUserJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddaUserJButton.setText("Add a User ");
        AddaUserJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddaUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddaUserJButtonActionPerformed(evt);
            }
        });

        ChangePasswordJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChangePasswordJButton.setText("ChangePassword");
        ChangePasswordJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChangePasswordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserMenujPanelLayout = new javax.swing.GroupLayout(UserMenujPanel);
        UserMenujPanel.setLayout(UserMenujPanelLayout);
        UserMenujPanelLayout.setHorizontalGroup(
            UserMenujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserMenujPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(UserMenujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChangePasswordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddaUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditaUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReportsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        UserMenujPanelLayout.setVerticalGroup(
            UserMenujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMenujPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddaUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditaUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangePasswordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        AssetMenujPanel.setBackground(new java.awt.Color(153, 153, 153));

        ViewAllAssetsJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewAllAssetsJButton.setText("View All Assets");
        ViewAllAssetsJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewAllAssetsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllAssetsJButtonActionPerformed(evt);
            }
        });

        AddanAssetJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddanAssetJButton.setText("Add an Asset");
        AddanAssetJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddanAssetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddanAssetJButtonActionPerformed(evt);
            }
        });

        EditanAssetJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditanAssetJButton.setText("Edit an Asset");
        EditanAssetJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditanAssetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditanAssetJButtonActionPerformed(evt);
            }
        });

        RetireanAssetJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RetireanAssetJButton.setText("Retire an Asset");
        RetireanAssetJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RetireanAssetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetireanAssetJButtonActionPerformed(evt);
            }
        });

        RepairanAssetsJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RepairanAssetsJButton.setText("Repair an Assets");
        RepairanAssetsJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RepairanAssetsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepairanAssetsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AssetMenujPanelLayout = new javax.swing.GroupLayout(AssetMenujPanel);
        AssetMenujPanel.setLayout(AssetMenujPanelLayout);
        AssetMenujPanelLayout.setHorizontalGroup(
            AssetMenujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssetMenujPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(AssetMenujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RepairanAssetsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RetireanAssetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAllAssetsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddanAssetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditanAssetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        AssetMenujPanelLayout.setVerticalGroup(
            AssetMenujPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssetMenujPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewAllAssetsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepairanAssetsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddanAssetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditanAssetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RetireanAssetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(AssetMenujPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserMenujPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserMenujPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AssetMenujPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReportsJButtonChangePasswordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsJButtonChangePasswordJButtonActionPerformed
        // go to report panel
        Main.login.setContentPane(new ReportsJPanel());
        Main.login.pack();
    }//GEN-LAST:event_ReportsJButtonChangePasswordJButtonActionPerformed

    private void ExitJButtonChangePasswordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitJButtonChangePasswordJButtonActionPerformed

        try {
            Main.login.setContentPane(new LoginJPanel());
            Main.login.pack();
        } catch (Exception e) {
            System.out.println("Something happend wrong! trying to save data.");
        } finally {
            Main.SaveAllData();
        }

    }//GEN-LAST:event_ExitJButtonChangePasswordJButtonActionPerformed

    private void ViewAllAssetsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllAssetsJButtonActionPerformed
        // go to view all assets panel
        Main.login.setContentPane(new ViewAllAssetsJPanel());
        Main.login.pack();
    }//GEN-LAST:event_ViewAllAssetsJButtonActionPerformed

    private void EditaUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditaUserJButtonActionPerformed
        // go to edit a user panel
        Main.login.setContentPane(new EditaUserJPanel());
        Main.login.pack();
    }//GEN-LAST:event_EditaUserJButtonActionPerformed

    private void AddanAssetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddanAssetJButtonActionPerformed
        // go to add an asset panel
        Main.login.setContentPane(new AddanAssetJPanel());
        Main.login.pack();
    }//GEN-LAST:event_AddanAssetJButtonActionPerformed

    private void EditanAssetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditanAssetJButtonActionPerformed
        // go to edit an asset panel
        Main.login.setContentPane(new EditanAssetJPanel());
        Main.login.pack();
    }//GEN-LAST:event_EditanAssetJButtonActionPerformed

    private void RetireanAssetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetireanAssetJButtonActionPerformed
        // go to retire an asset panel
        Main.login.setContentPane(new RetireanAssetJPanel());
        Main.login.pack();
    }//GEN-LAST:event_RetireanAssetJButtonActionPerformed

    private void AddaUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddaUserJButtonActionPerformed
        // go to sign in panel
        Main.login.setContentPane(new AddaUser());
        Main.login.pack();
    }//GEN-LAST:event_AddaUserJButtonActionPerformed

    private void ChangePasswordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordJButtonActionPerformed
        // go to change password panel
        Main.login.setContentPane(new ChangePasswordJPanel());
        Main.login.pack();
    }//GEN-LAST:event_ChangePasswordJButtonActionPerformed

    private void RepairanAssetsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepairanAssetsJButtonActionPerformed
        // go to repair an asset panel
        Main.login.setContentPane(new RepairanAssetJPanel());
        Main.login.pack();
    }//GEN-LAST:event_RepairanAssetsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddaUserJButton;
    private javax.swing.JButton AddanAssetJButton;
    private javax.swing.JPanel AssetMenujPanel;
    private javax.swing.JButton ChangePasswordJButton;
    private javax.swing.JButton EditaUserJButton;
    private javax.swing.JButton EditanAssetJButton;
    private javax.swing.JButton ExitJButton;
    private javax.swing.JButton RepairanAssetsJButton;
    private javax.swing.JButton ReportsJButton;
    private javax.swing.JButton RetireanAssetJButton;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JPanel UserMenujPanel;
    private javax.swing.JButton ViewAllAssetsJButton;
    // End of variables declaration//GEN-END:variables
}
