/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Options;

import Program.Main;
import Program.Objects.Computer;
import Program.Objects.Printer;
import Program.Objects.Switch;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author moham
 */
public class AddanAssetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddanAssetJPanel
     */
    String location[] = new String[3];
    String model = "";
    String cpu = "";
    String ram = "";
    String hard = "";
    String graphic = "";
    String date;
    int portnumber = 0;
    String state = "Working_Fine";
    boolean manageable = true;
    boolean coloreable = true;

    public AddanAssetJPanel() {

        initComponents();
        Main.login.setMinimumSize(this.getMinimumSize());
        AddPCjPanel.setVisible(true);
        AddPrinterjPanel.setVisible(false);
        AddSwitchjPanel.setVisible(false);
        ManageableButtonGroup.setSelected(ManageablejRadioButton.getModel(), true);
        ColorableButtonGroup.setSelected(YesjRadioButton.getModel(), true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageableButtonGroup = new javax.swing.ButtonGroup();
        ColorableButtonGroup = new javax.swing.ButtonGroup();
        TitlejLabel = new javax.swing.JLabel();
        AssetjPanel = new javax.swing.JPanel();
        AssetsjComboBox = new javax.swing.JComboBox();
        AssetTypejLabel = new javax.swing.JLabel();
        CollegejTextField = new javax.swing.JTextField();
        OwnerjTextField = new javax.swing.JTextField();
        CamajLabel1 = new javax.swing.JLabel();
        CamajLabel2 = new javax.swing.JLabel();
        PlacejTextField = new javax.swing.JTextField();
        ModeljLabel = new javax.swing.JLabel();
        ModeljTextField = new javax.swing.JTextField();
        StatejLabel = new javax.swing.JLabel();
        StatejComboBox = new javax.swing.JComboBox();
        LocationjLabel = new javax.swing.JLabel();
        SwapjLayeredPane = new javax.swing.JLayeredPane();
        AddPCjPanel = new javax.swing.JPanel();
        MainMenujButton1 = new javax.swing.JButton();
        AddPCjButton = new javax.swing.JButton();
        CPUjLabel = new javax.swing.JLabel();
        HardjLabel = new javax.swing.JLabel();
        RAMjLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CPUjTextField = new javax.swing.JTextField();
        HardjTextField = new javax.swing.JTextField();
        RAMjTextField = new javax.swing.JTextField();
        GraphicjTextField = new javax.swing.JTextField();
        AddSwitchjPanel = new javax.swing.JPanel();
        MainMenujButton2 = new javax.swing.JButton();
        AddSwitchjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PortNumberjSpinner = new javax.swing.JSpinner();
        ManageablejRadioButton = new javax.swing.JRadioButton();
        UnmanageablejRadioButton = new javax.swing.JRadioButton();
        ManageablejLabel = new javax.swing.JLabel();
        AddPrinterjPanel = new javax.swing.JPanel();
        MainMenujButton3 = new javax.swing.JButton();
        AddPrinterjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        YesjRadioButton = new javax.swing.JRadioButton();
        NojRadioButton = new javax.swing.JRadioButton();

        TitlejLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitlejLabel.setText("Add an Asset");

        AssetsjComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AssetsjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer", "Switch", "Printer" }));
        AssetsjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssetsjComboBoxActionPerformed(evt);
            }
        });

        AssetTypejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssetTypejLabel.setText("Asset type :");

        CollegejTextField.setText("College");
        CollegejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CollegejTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CollegejTextFieldFocusLost(evt);
            }
        });

        OwnerjTextField.setText("Owner");
        OwnerjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OwnerjTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                OwnerjTextFieldFocusLost(evt);
            }
        });

        CamajLabel1.setText(",");

        CamajLabel2.setText(",");

        PlacejTextField.setText("Place");
        PlacejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PlacejTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PlacejTextFieldFocusLost(evt);
            }
        });

        ModeljLabel.setText("Model :");

        ModeljTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ModeljTextFieldFocusLost(evt);
            }
        });

        StatejLabel.setText("State :");

        StatejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Working and Fine", "Working but Broken" }));
        StatejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatejComboBoxActionPerformed(evt);
            }
        });

        LocationjLabel.setText("Location :");

        javax.swing.GroupLayout AssetjPanelLayout = new javax.swing.GroupLayout(AssetjPanel);
        AssetjPanel.setLayout(AssetjPanelLayout);
        AssetjPanelLayout.setHorizontalGroup(
            AssetjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssetjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModeljLabel)
                .addGap(6, 6, 6)
                .addComponent(ModeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(StatejLabel)
                .addGap(4, 4, 4)
                .addComponent(StatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AssetjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AssetTypejLabel)
                .addGap(4, 4, 4)
                .addComponent(AssetsjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AssetjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LocationjLabel)
                .addGap(10, 10, 10)
                .addComponent(CollegejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(CamajLabel1)
                .addGap(4, 4, 4)
                .addComponent(OwnerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(CamajLabel2)
                .addGap(4, 4, 4)
                .addComponent(PlacejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AssetjPanelLayout.setVerticalGroup(
            AssetjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssetjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AssetjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssetjPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(AssetTypejLabel))
                    .addComponent(AssetsjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AssetjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AssetjPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(AssetjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AssetjPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(ModeljLabel))
                            .addComponent(StatejLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(AssetjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CollegejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OwnerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlacejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AssetjPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(AssetjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocationjLabel)
                            .addComponent(CamajLabel1)
                            .addComponent(CamajLabel2)))))
        );

        CollegejTextField.setForeground(Color.gray);
        OwnerjTextField.setForeground(Color.gray);
        PlacejTextField.setForeground(Color.gray);

        SwapjLayeredPane.setPreferredSize(new java.awt.Dimension(390, 151));

        AddPCjPanel.setMaximumSize(new java.awt.Dimension(390, 151));
        AddPCjPanel.setMinimumSize(new java.awt.Dimension(390, 151));
        AddPCjPanel.setPreferredSize(new java.awt.Dimension(390, 151));

        MainMenujButton1.setText("Main Menu");
        MainMenujButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenujButton1ActionPerformed(evt);
            }
        });

        AddPCjButton.setText("Add");
        AddPCjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPCjButtonActionPerformed(evt);
            }
        });

        CPUjLabel.setText("CPU :");

        HardjLabel.setText("Hard :");

        RAMjLabel.setText("RAM :");

        jLabel4.setText("Graphic :");

        CPUjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CPUjTextFieldFocusLost(evt);
            }
        });

        HardjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                HardjTextFieldFocusLost(evt);
            }
        });

        RAMjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RAMjTextFieldFocusLost(evt);
            }
        });

        GraphicjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                GraphicjTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout AddPCjPanelLayout = new javax.swing.GroupLayout(AddPCjPanel);
        AddPCjPanel.setLayout(AddPCjPanelLayout);
        AddPCjPanelLayout.setHorizontalGroup(
            AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPCjPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HardjLabel)
                    .addComponent(CPUjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CPUjTextField)
                    .addComponent(HardjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4)
                    .addComponent(RAMjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RAMjTextField)
                    .addComponent(GraphicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(AddPCjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddPCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainMenujButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddPCjPanelLayout.setVerticalGroup(
            AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPCjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPUjLabel)
                    .addComponent(RAMjLabel)
                    .addComponent(CPUjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RAMjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HardjLabel)
                    .addComponent(jLabel4)
                    .addComponent(HardjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GraphicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddPCjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainMenujButton1)
                    .addComponent(AddPCjButton))
                .addGap(26, 26, 26))
        );

        AddSwitchjPanel.setMaximumSize(new java.awt.Dimension(390, 151));
        AddSwitchjPanel.setMinimumSize(new java.awt.Dimension(390, 151));
        AddSwitchjPanel.setPreferredSize(new java.awt.Dimension(390, 151));

        MainMenujButton2.setText("Main Menu");
        MainMenujButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenujButton2ActionPerformed(evt);
            }
        });

        AddSwitchjButton.setText("Add");
        AddSwitchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSwitchjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Port Number :");

        PortNumberjSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        PortNumberjSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PortNumberjSpinnerStateChanged(evt);
            }
        });

        ManageableButtonGroup.add(ManageablejRadioButton);
        ManageablejRadioButton.setText("Yes");

        ManageableButtonGroup.add(UnmanageablejRadioButton);
        UnmanageablejRadioButton.setText("No");

        ManageablejLabel.setText("Manageable :");

        javax.swing.GroupLayout AddSwitchjPanelLayout = new javax.swing.GroupLayout(AddSwitchjPanel);
        AddSwitchjPanel.setLayout(AddSwitchjPanelLayout);
        AddSwitchjPanelLayout.setHorizontalGroup(
            AddSwitchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSwitchjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddSwitchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSwitchjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(PortNumberjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddSwitchjPanelLayout.createSequentialGroup()
                        .addComponent(ManageablejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ManageablejRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UnmanageablejRadioButton))
                    .addGroup(AddSwitchjPanelLayout.createSequentialGroup()
                        .addComponent(AddSwitchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MainMenujButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddSwitchjPanelLayout.setVerticalGroup(
            AddSwitchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSwitchjPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(AddSwitchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PortNumberjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddSwitchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageablejRadioButton)
                    .addComponent(UnmanageablejRadioButton)
                    .addComponent(ManageablejLabel))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(AddSwitchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainMenujButton2)
                    .addComponent(AddSwitchjButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        AddPrinterjPanel.setMaximumSize(new java.awt.Dimension(390, 151));
        AddPrinterjPanel.setMinimumSize(new java.awt.Dimension(390, 151));
        AddPrinterjPanel.setPreferredSize(new java.awt.Dimension(390, 151));

        MainMenujButton3.setText("Main Menu");
        MainMenujButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenujButton3ActionPerformed(evt);
            }
        });

        AddPrinterjButton.setText("Add");
        AddPrinterjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPrinterjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Color Print :");

        ColorableButtonGroup.add(YesjRadioButton);
        YesjRadioButton.setText("Yes");

        ColorableButtonGroup.add(NojRadioButton);
        NojRadioButton.setText("No");

        javax.swing.GroupLayout AddPrinterjPanelLayout = new javax.swing.GroupLayout(AddPrinterjPanel);
        AddPrinterjPanel.setLayout(AddPrinterjPanelLayout);
        AddPrinterjPanelLayout.setHorizontalGroup(
            AddPrinterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPrinterjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddPrinterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPrinterjPanelLayout.createSequentialGroup()
                        .addComponent(AddPrinterjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MainMenujButton3))
                    .addGroup(AddPrinterjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(YesjRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(NojRadioButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddPrinterjPanelLayout.setVerticalGroup(
            AddPrinterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPrinterjPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AddPrinterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(YesjRadioButton)
                    .addComponent(NojRadioButton))
                .addGap(53, 53, 53)
                .addGroup(AddPrinterjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainMenujButton3)
                    .addComponent(AddPrinterjButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SwapjLayeredPaneLayout = new javax.swing.GroupLayout(SwapjLayeredPane);
        SwapjLayeredPane.setLayout(SwapjLayeredPaneLayout);
        SwapjLayeredPaneLayout.setHorizontalGroup(
            SwapjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SwapjLayeredPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(SwapjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddPCjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(AddPrinterjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(AddSwitchjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)))
        );
        SwapjLayeredPaneLayout.setVerticalGroup(
            SwapjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SwapjLayeredPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(SwapjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddPrinterjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddSwitchjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddPCjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        SwapjLayeredPane.setLayer(AddPCjPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SwapjLayeredPane.setLayer(AddSwitchjPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SwapjLayeredPane.setLayer(AddPrinterjPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitlejLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(SwapjLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
            .addComponent(AssetjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssetjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SwapjLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AssetsjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssetsjComboBoxActionPerformed

        // switch between panels
        switch (AssetsjComboBox.getSelectedIndex()) {
            case 0:
                AddPCjPanel.setVisible(true);
                AddPrinterjPanel.setVisible(false);
                AddSwitchjPanel.setVisible(false);
                break;
            case 1:
                AddPCjPanel.setVisible(false);
                AddSwitchjPanel.setVisible(true);
                AddPrinterjPanel.setVisible(false);
                break;
            case 2:
                AddPCjPanel.setVisible(false);
                AddSwitchjPanel.setVisible(false);
                AddPrinterjPanel.setVisible(true);
                break;
        }

    }//GEN-LAST:event_AssetsjComboBoxActionPerformed

    private void CollegejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CollegejTextFieldFocusGained

        if (CollegejTextField.getText().equals("College")) {
            CollegejTextField.setText("");
            CollegejTextField.setForeground(Color.black);
        }

    }//GEN-LAST:event_CollegejTextFieldFocusGained

    private void CollegejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CollegejTextFieldFocusLost

        if (CollegejTextField.getText().equals("")) {
            CollegejTextField.setText("College");
            CollegejTextField.setForeground(Color.gray);
        }
        location[0] = CollegejTextField.getText();

    }//GEN-LAST:event_CollegejTextFieldFocusLost

    private void OwnerjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OwnerjTextFieldFocusGained

        if (OwnerjTextField.getText().equals("Owner")) {
            OwnerjTextField.setText("");
            OwnerjTextField.setForeground(Color.black);
        }

    }//GEN-LAST:event_OwnerjTextFieldFocusGained

    private void OwnerjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OwnerjTextFieldFocusLost

        if (OwnerjTextField.getText().equals("")) {
            OwnerjTextField.setText("Owner");
            OwnerjTextField.setForeground(Color.gray);
        }
        location[1] = OwnerjTextField.getText();

    }//GEN-LAST:event_OwnerjTextFieldFocusLost

    private void PlacejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PlacejTextFieldFocusGained

        if (PlacejTextField.getText().equals("Place")) {
            PlacejTextField.setText("");
            PlacejTextField.setForeground(Color.black);
        }

    }//GEN-LAST:event_PlacejTextFieldFocusGained

    private void PlacejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PlacejTextFieldFocusLost

        if (PlacejTextField.getText().equals("")) {
            PlacejTextField.setText("Place");
            PlacejTextField.setForeground(Color.gray);
        }
        location[2] = PlacejTextField.getText();

    }//GEN-LAST:event_PlacejTextFieldFocusLost

    private void MainMenujButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenujButton2ActionPerformed
        Main.BacktoMainMenu();
    }//GEN-LAST:event_MainMenujButton2ActionPerformed

    private void MainMenujButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenujButton3ActionPerformed
        Main.BacktoMainMenu();
    }//GEN-LAST:event_MainMenujButton3ActionPerformed

    private void MainMenujButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenujButton1ActionPerformed
        Main.BacktoMainMenu();
    }//GEN-LAST:event_MainMenujButton1ActionPerformed

    private void AddSwitchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSwitchjButtonActionPerformed

        try {
            ready();
            manageable = ManageableButtonGroup.getSelection().equals(ManageablejRadioButton.getModel());
            Switch Switch = new Switch(model, date, location, state, portnumber, manageable);
            Main.switches.add(Switch);
            Main.UpdateAssets(0);
            JOptionPane.showInternalMessageDialog(this, "Switch " + model +
                    " has been added successfully.", "Add Asset", 1);
            Main.BacktoMainMenu();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Main.login, e.getMessage(), "Error", 0);
        }

    }//GEN-LAST:event_AddSwitchjButtonActionPerformed

    private void ModeljTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModeljTextFieldFocusLost

        if (!ModeljTextField.getText().equals("")) {
            model = ModeljTextField.getText();
        }

    }//GEN-LAST:event_ModeljTextFieldFocusLost

    private void CPUjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CPUjTextFieldFocusLost

        if (!CPUjTextField.getText().equals("")) {
            cpu = CPUjTextField.getText();
        }

    }//GEN-LAST:event_CPUjTextFieldFocusLost

    private void RAMjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RAMjTextFieldFocusLost

        if (!RAMjTextField.getText().equals("")) {
            ram = RAMjTextField.getText();
        }

    }//GEN-LAST:event_RAMjTextFieldFocusLost

    private void HardjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HardjTextFieldFocusLost

        if (!HardjTextField.getText().equals("")) {
            hard = HardjTextField.getText();
        }

    }//GEN-LAST:event_HardjTextFieldFocusLost

    private void GraphicjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GraphicjTextFieldFocusLost

        if (!GraphicjTextField.getText().equals("")) {
            graphic = GraphicjTextField.getText();
        }

    }//GEN-LAST:event_GraphicjTextFieldFocusLost

    private void AddPCjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPCjButtonActionPerformed

        try {
            ready();
            Computer computer = new Computer(model, date, location, state, cpu, ram, hard, graphic);
            Main.computers.add(computer);
            Main.UpdateAssets(0);
            JOptionPane.showInternalMessageDialog(this, "Computer " + model +
                    " has been added successfully.", "Add Asset", 1);
            Main.BacktoMainMenu();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(Main.login, e.getMessage(), "Error", 0);
        }

    }//GEN-LAST:event_AddPCjButtonActionPerformed

    private void StatejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatejComboBoxActionPerformed

        switch (StatejComboBox.getSelectedIndex()) {
            case 0:
                state = "Working_Fine";
                break;
            case 1:
                state = "Working_Broken";
                break;
        }

    }//GEN-LAST:event_StatejComboBoxActionPerformed

    private void AddPrinterjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPrinterjButtonActionPerformed

        try {
            ready();
            coloreable = ColorableButtonGroup.getSelection().equals(YesjRadioButton.getModel());
            Printer printer = new Printer(model, date, location, state, coloreable);
            Main.printers.add(printer);
            Main.UpdateAssets(0);
            JOptionPane.showInternalMessageDialog(this, "Printer " + model +
                    " has been added successfully.", "Add Asset", 1);
            Main.BacktoMainMenu();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(Main.login, e.getMessage(), "Error", 0);
        }

    }//GEN-LAST:event_AddPrinterjButtonActionPerformed

    private void PortNumberjSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PortNumberjSpinnerStateChanged
        portnumber = (Integer) PortNumberjSpinner.getValue();
    }//GEN-LAST:event_PortNumberjSpinnerStateChanged

    private void ready() throws IllegalStateException {

        if (model.equals("") || location[0].equals("") || location[1].equals("")
                || location[2].equals("")) {
            throw new IllegalStateException("One or some of asset fields are invalid!");
        }
        if (AssetsjComboBox.getSelectedIndex() == 0 && (cpu.equals("") || ram.equals("")
                || hard.equals("") || graphic.equals(""))) {
            throw new IllegalStateException("One or some of computer Fields are invalid!");
        }
        if (AssetsjComboBox.getSelectedIndex() == 1 && portnumber <= 1) {
            throw new IllegalStateException("Port Number must be higher than 1!");
        }        
        date = new Date().toGMTString();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPCjButton;
    private javax.swing.JPanel AddPCjPanel;
    private javax.swing.JButton AddPrinterjButton;
    private javax.swing.JPanel AddPrinterjPanel;
    private javax.swing.JButton AddSwitchjButton;
    private javax.swing.JPanel AddSwitchjPanel;
    private javax.swing.JLabel AssetTypejLabel;
    private javax.swing.JPanel AssetjPanel;
    private javax.swing.JComboBox AssetsjComboBox;
    private javax.swing.JLabel CPUjLabel;
    private javax.swing.JTextField CPUjTextField;
    private javax.swing.JLabel CamajLabel1;
    private javax.swing.JLabel CamajLabel2;
    private javax.swing.JTextField CollegejTextField;
    private javax.swing.ButtonGroup ColorableButtonGroup;
    private javax.swing.JTextField GraphicjTextField;
    private javax.swing.JLabel HardjLabel;
    private javax.swing.JTextField HardjTextField;
    private javax.swing.JLabel LocationjLabel;
    private javax.swing.JButton MainMenujButton1;
    private javax.swing.JButton MainMenujButton2;
    private javax.swing.JButton MainMenujButton3;
    private javax.swing.ButtonGroup ManageableButtonGroup;
    private javax.swing.JLabel ManageablejLabel;
    private javax.swing.JRadioButton ManageablejRadioButton;
    private javax.swing.JLabel ModeljLabel;
    private javax.swing.JTextField ModeljTextField;
    private javax.swing.JRadioButton NojRadioButton;
    private javax.swing.JTextField OwnerjTextField;
    private javax.swing.JTextField PlacejTextField;
    private javax.swing.JSpinner PortNumberjSpinner;
    private javax.swing.JLabel RAMjLabel;
    private javax.swing.JTextField RAMjTextField;
    private javax.swing.JComboBox StatejComboBox;
    private javax.swing.JLabel StatejLabel;
    private javax.swing.JLayeredPane SwapjLayeredPane;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JRadioButton UnmanageablejRadioButton;
    private javax.swing.JRadioButton YesjRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
