/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Options;

import Program.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author MAJ
 */
public class ChangePasswordJPanel extends javax.swing.JPanel {

    String CurrentPassword = "";
    String NewPassword = "";
    String ConfirmNewPassword = "";
    boolean PassChk1 = false;
    boolean PassChk2 = false;
    boolean PassChk3 = false;

    /**
     * Creates new form ChangePasswordJPanel
     */
    public ChangePasswordJPanel() {
        initComponents();
        Main.login.setMinimumSize(this.getMinimumSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlejLabel = new javax.swing.JLabel();
        CurrentPasswordjLabel = new javax.swing.JLabel();
        CurrentPasswordjPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewPasswordjPasswordField = new javax.swing.JPasswordField();
        ConfirmNewPasswordjPasswordField = new javax.swing.JPasswordField();
        CurrentPasswordErrorjLabel = new javax.swing.JLabel();
        NewPasswordErrorjLabel = new javax.swing.JLabel();
        ConfirmNewPasswordErrorjLabel = new javax.swing.JLabel();
        ChangejButton = new javax.swing.JButton();
        MainMenujButton = new javax.swing.JButton();

        TitlejLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitlejLabel.setText("Change Password");

        CurrentPasswordjLabel.setText("Current Password :");

        CurrentPasswordjPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CurrentPasswordjPasswordFieldFocusLost(evt);
            }
        });

        jLabel1.setText("New Password :");

        jLabel2.setText("Confirm new password :");

        NewPasswordjPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewPasswordjPasswordFieldFocusLost(evt);
            }
        });

        ConfirmNewPasswordjPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmNewPasswordjPasswordFieldFocusLost(evt);
            }
        });

        CurrentPasswordErrorjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CurrentPasswordErrorjLabel.setForeground(new java.awt.Color(255, 0, 0));
        CurrentPasswordErrorjLabel.setText("!");

        NewPasswordErrorjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewPasswordErrorjLabel.setForeground(new java.awt.Color(255, 0, 0));
        NewPasswordErrorjLabel.setText("!");

        ConfirmNewPasswordErrorjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConfirmNewPasswordErrorjLabel.setForeground(new java.awt.Color(255, 0, 0));
        ConfirmNewPasswordErrorjLabel.setText("!");

        ChangejButton.setText("Change");
        ChangejButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChangejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangejButtonActionPerformed(evt);
            }
        });

        MainMenujButton.setText("Main Menu");
        MainMenujButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MainMenujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TitlejLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CurrentPasswordjLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewPasswordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(NewPasswordErrorjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConfirmNewPasswordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(ConfirmNewPasswordErrorjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurrentPasswordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(CurrentPasswordErrorjLabel)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(MainMenujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentPasswordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentPasswordjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CurrentPasswordErrorjLabel))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewPasswordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(NewPasswordErrorjLabel))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmNewPasswordErrorjLabel)
                    .addComponent(ConfirmNewPasswordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(MainMenujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        CurrentPasswordErrorjLabel.setVisible(false);
        CurrentPasswordErrorjLabel.setToolTipText("Password invalid or worng!");
        NewPasswordErrorjLabel.setVisible(false);
        NewPasswordErrorjLabel.setToolTipText("Invalid Password!");
        ConfirmNewPasswordErrorjLabel.setVisible(false);
        ConfirmNewPasswordErrorjLabel.setToolTipText("Passwords are not same!");
    }// </editor-fold>//GEN-END:initComponents

    private void ChangejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangejButtonActionPerformed

        if (CurrentPassword.equals("") || !CurrentPassword.equals(Main.login.getUser().getPassword())) {
            CurrentPasswordErrorjLabel.setVisible(true);
            PassChk1 = false;
        } else {
            PassChk1 = true;
        }
        if (NewPassword.equals("")) {
            NewPasswordErrorjLabel.setVisible(true);
            PassChk2 = false;
        } else {
            PassChk2 = true;
        }
        if (ConfirmNewPassword.equals("") || !ConfirmNewPassword.equals(NewPassword)) {
            ConfirmNewPasswordErrorjLabel.setVisible(true);
            PassChk3 = false;
        } else {
            PassChk3 = true;
        }
        if (PassChk1 && PassChk2 && PassChk3) {
            // setting new password
            int i = JOptionPane.showConfirmDialog(this, "Do you want to Change your password?", 
                    "Change Password", 0);
            if (JOptionPane.YES_OPTION == i) {
                Main.login.getUser().SetPassword(NewPassword);
                Main.BacktoMainMenu();
            }
        }

    }//GEN-LAST:event_ChangejButtonActionPerformed

    private void MainMenujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenujButtonActionPerformed
        Main.BacktoMainMenu();
    }//GEN-LAST:event_MainMenujButtonActionPerformed

    private void CurrentPasswordjPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CurrentPasswordjPasswordFieldFocusLost
        CurrentPassword = CurrentPasswordjPasswordField.getText();
        CurrentPasswordErrorjLabel.setVisible(false);
    }//GEN-LAST:event_CurrentPasswordjPasswordFieldFocusLost

    private void NewPasswordjPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewPasswordjPasswordFieldFocusLost
        NewPassword = NewPasswordjPasswordField.getText();
        NewPasswordErrorjLabel.setVisible(false);
    }//GEN-LAST:event_NewPasswordjPasswordFieldFocusLost

    private void ConfirmNewPasswordjPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmNewPasswordjPasswordFieldFocusLost
        ConfirmNewPassword = ConfirmNewPasswordjPasswordField.getText();
        ConfirmNewPasswordErrorjLabel.setVisible(false);
    }//GEN-LAST:event_ConfirmNewPasswordjPasswordFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangejButton;
    private javax.swing.JLabel ConfirmNewPasswordErrorjLabel;
    private javax.swing.JPasswordField ConfirmNewPasswordjPasswordField;
    private javax.swing.JLabel CurrentPasswordErrorjLabel;
    private javax.swing.JLabel CurrentPasswordjLabel;
    private javax.swing.JPasswordField CurrentPasswordjPasswordField;
    private javax.swing.JButton MainMenujButton;
    private javax.swing.JLabel NewPasswordErrorjLabel;
    private javax.swing.JPasswordField NewPasswordjPasswordField;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
