/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Options;

import GUI.AdminMenuJPanel;
import Program.Enums.UserRank;
import Program.Main;
import Program.Objects.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author moham
 */
public class EditaUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditanAssetJPanel1
     */
    
    User user;
    User[] users_arr = new User[Main.users.size()];
    
    public EditaUserJPanel() {
        users_arr = Main.users.toArray(users_arr);
        initComponents();
        Main.login.setMinimumSize(this.getMinimumSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlejLabel = new javax.swing.JLabel();
        ListjPanel = new javax.swing.JPanel();
        ListTitlejLabel = new javax.swing.JLabel();
        SearchjLabel = new javax.swing.JLabel();
        SearchjTextField = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        UsernamejLabel = new javax.swing.JLabel();
        UsernamejTextField = new javax.swing.JTextField();
        PasswordjLabel = new javax.swing.JLabel();
        PasswordjTextField = new javax.swing.JTextField();
        RankjLabel = new javax.swing.JLabel();
        RankjComboBox = new javax.swing.JComboBox();
        MainMenujButton = new javax.swing.JButton();
        EditjButton = new javax.swing.JButton();

        TitlejLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitlejLabel.setText("Edit a User");

        ListTitlejLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ListTitlejLabel.setText("Users");

        SearchjLabel.setText("Search ID :");

        jList.setModel(new javax.swing.AbstractListModel() {
            User[] users = users_arr;
            public int getSize() { return users_arr.length; }
            public Object getElementAt(int i) { return users_arr[i]; }
        });
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane.setViewportView(jList);

        javax.swing.GroupLayout ListjPanelLayout = new javax.swing.GroupLayout(ListjPanel);
        ListjPanel.setLayout(ListjPanelLayout);
        ListjPanelLayout.setHorizontalGroup(
            ListjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(ListjPanelLayout.createSequentialGroup()
                .addComponent(SearchjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListTitlejLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListjPanelLayout.setVerticalGroup(
            ListjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListTitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchjLabel)
                    .addComponent(SearchjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
        );

        SearchjTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                updatelist();
            }
            public void removeUpdate(DocumentEvent e) {
                updatelist();
            }
            public void insertUpdate(DocumentEvent e) {
                updatelist();
            }
        });

        UsernamejLabel.setText("User Name :");

        PasswordjLabel.setText("Password :");

        RankjLabel.setText("Rank :");

        RankjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "User" }));

        MainMenujButton.setText("Main Menu");
        MainMenujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenujButtonActionPerformed(evt);
            }
        });

        EditjButton.setText("Edit");
        EditjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitlejLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernamejLabel)
                            .addComponent(PasswordjLabel)
                            .addComponent(RankjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RankjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordjTextField)
                            .addComponent(UsernamejTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MainMenujButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(ListjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ListjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UsernamejLabel)
                            .addComponent(UsernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordjLabel)
                            .addComponent(PasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RankjLabel)
                            .addComponent(RankjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MainMenujButton)
                            .addComponent(EditjButton))
                        .addGap(19, 19, 19))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged

        if (evt.getValueIsAdjusting()) {//This line prevents double events
            user = (User) jList.getSelectedValue();
            // setting previous information
            UsernamejTextField.setText(user.getUsername());
            PasswordjTextField.setText(user.getPassword());
            if (user.getRank().equals(UserRank.Administrator)){
                RankjComboBox.setSelectedIndex(0);
            } else {
                RankjComboBox.setSelectedIndex(1);
            }
        }
        
    }//GEN-LAST:event_jListValueChanged

    private void MainMenujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenujButtonActionPerformed
        Main.login.setContentPane(new AdminMenuJPanel());
        Main.login.pack();
    }//GEN-LAST:event_MainMenujButtonActionPerformed

    private void EditjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditjButtonActionPerformed
        
        try {
            ready();
            int i = JOptionPane.showConfirmDialog(Main.login, "Do you want to edit this user?", "Edit User", 0);
            if (JOptionPane.YES_OPTION == i) {
                user.SetPassword(PasswordjTextField.getText());
            user.setUsername(UsernamejTextField.getText());
            if (RankjComboBox.getSelectedIndex() == 0){
                user.setRank(UserRank.Administrator.toString());
            } else {
                user.setRank(UserRank.NormalUser.toString());
            }
                Main.BacktoMainMenu();
            }
        } catch (IllegalStateException e){
            JOptionPane.showMessageDialog(Main.login, e.getMessage(), "Error", 0);
        }
        
    }//GEN-LAST:event_EditjButtonActionPerformed

        void updatelist() {
        
        ArrayList <User> NewList = new ArrayList();
        for (User u : Main.users){
            if (u.toString().startsWith(SearchjTextField.getText())){
                NewList.add(u);
            }           
        }
        jList.setListData(NewList.toArray());
        
    }

        private void ready() throws IllegalStateException {
        
            if (UsernamejTextField.getText().equals("")){
                throw new IllegalStateException("Username field is blank!");
            }
            if (PasswordjTextField.getText().equals("Password field is blank!")){
                throw new IllegalStateException();
            }
            
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditjButton;
    private javax.swing.JLabel ListTitlejLabel;
    private javax.swing.JPanel ListjPanel;
    private javax.swing.JButton MainMenujButton;
    private javax.swing.JLabel PasswordjLabel;
    private javax.swing.JTextField PasswordjTextField;
    private javax.swing.JComboBox RankjComboBox;
    private javax.swing.JLabel RankjLabel;
    private javax.swing.JLabel SearchjLabel;
    private javax.swing.JTextField SearchjTextField;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JLabel UsernamejLabel;
    private javax.swing.JTextField UsernamejTextField;
    private javax.swing.JList jList;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables

    
}
